[package]
name = "muninn-gate-firmware"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "muninn-gate"
path = "src/main.rs"

[features]
default = ["heltec-v4"]
esp32s3 = ["heltec-v4"]
serial-json = [
    "muninn-gate-board-heltec-v4?/serial-json",
    "muninn-gate-core/serial-json",
]
heltec-v4 = [
    "dep:esp-backtrace",
    "dep:esp-hal",
    "dep:muninn-gate-board-heltec-v4",
]
bifrost-pros3 = [
    "dep:esp-backtrace",
    "dep:esp-hal",
    "dep:muninn-gate-board-bifrost-pros3",
]

[dependencies]
muninn-gate-board-bifrost-pros3 = { workspace = true, optional = true }
muninn-gate-board-heltec-v4 = { workspace = true, optional = true }
muninn-gate-core.workspace = true

esp-backtrace = { workspace = true, optional = true, features = ["esp32s3", "panic-handler", "println"] }
esp-hal = { workspace = true, optional = true, features = ["esp32s3", "unstable"] }
